config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-scg:
      branch: master
      repo: https://github.com/ARGOeu/argo-scg
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-scg git:
        commands:
        - /usr/bin/env sh .sqa/script.nutmeg_proactive_seal.sh
        container: qc.acc_indigo_proactive_crane
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-scg find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.rose_authentic_mandrill.sh
        container: qc.doc_ultramarine_calm_moose
      github.com/ARGOeu/argo-scg git:
        commands:
        - /usr/bin/env sh .sqa/script.hunter_shy_turtle.sh
        container: qc.doc_thistle_cheerful_raccoon
      github.com/ARGOeu/argo-scg markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fern_rugged_antelope.sh
        container: qc.doc_blush_realistic_skunk
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-scg licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gold_serene_kraken.sh
        container: qc.lic_pineapple_witty_baboon
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-scg bandit:
        commands:
        - /usr/bin/env sh .sqa/script.orange_persistent_nighthawk.sh
        container: qc.sec_mauve_stoic_seahorse
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-scg flake8:
        commands:
        - /usr/bin/env sh .sqa/script.amethyst_candid_hamster.sh
        container: qc.sty_amaranth_dramatic_tarantula
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-scg pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sand_decisive_groundhog.sh
        container: qc.uni_salmon_generous_panther
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-scg get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.papaya_melancholy_anaconda.sh
        container: qc.ver_chocolate_humorous_groundhog
timeout: 5400
